export default function Home() {
  return (
    <main>
      <section className="hero" id="inicio">
        <nav className="nav container" aria-label="Navegação principal"><a className="brand" href="#inicio"><span className="brand-mark">B</span><span>Bmax <em>Technology</em></span></a><div className="nav-links"><a href="#solucoes">Soluções</a><a href="#para-quem">Para seu negócio</a><a href="#contato">Contato</a></div><a className="button button-small" href="#catalogo">Baixar catálogo</a></nav>
        <div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">MOBILIDADE ELÉTRICA SEM COMPLICAÇÃO</p><h1>Carregue o futuro.<br /><span>Do seu jeito.</span></h1><p className="hero-text">Carregadores inteligentes para sua casa, empresa ou estacionamento. Escolha a solução certa e conte com um projeto pensado para a sua operação.</p><div className="hero-actions"><a className="button" href="#contato">Quero um orçamento</a><a className="text-link" href="#solucoes">Conhecer soluções <span>→</span></a></div><div className="proof"><span>✓</span> Atendimento consultivo para cada projeto</div></div><div className="charger-stage" aria-label="Ilustração de carregador elétrico Bmax"><div className="orb orb-one" /><div className="orb orb-two" /><div className="charger"><div className="charger-top"><i /><i /></div><div className="charger-screen">BMAX<br /><small>CHARGING</small></div><div className="charger-port" /><div className="charger-base" /></div><div className="cable" /><div className="plug" /><div className="stage-label"><b>Recarga inteligente</b><span>Para cada destino</span></div></div></div>
      </section>
      <section className="metrics container"><div><strong>Casa</strong><span>Recarga diária, simples e confiável</span></div><div><strong>Negócios</strong><span>Mais conveniência para clientes e equipes</span></div><div><strong>Frotas</strong><span>Infraestrutura que acompanha sua operação</span></div></section>
      <section className="solutions section container" id="solucoes"><div className="section-intro"><p className="eyebrow">UMA LINHA PARA CADA NECESSIDADE</p><h2>Energia que acompanha<br />o seu movimento.</h2></div><div className="solution-grid"><article className="solution-card home-card"><p>01 / RESIDENCIAL</p><h3>Para sua casa</h3><span>Carregadores compactos e inteligentes para tornar sua rotina mais prática.</span><a href="#catalogo">Ver modelos →</a><div className="mini-charger" /></article><article className="solution-card business-card"><p>02 / COMERCIAL</p><h3>Para o seu negócio</h3><span>Soluções para hotéis, padarias, condomínios e estacionamentos.</span><a href="#catalogo">Ver modelos →</a><div className="business-lines"><i /><i /><i /></div></article><article className="solution-card fleet-card"><p>03 / ALTA DEMANDA</p><h3>Para grandes operações</h3><span>Projetos escaláveis para shoppings, redes e frotas elétricas.</span><a href="#contato">Falar com especialista →</a><div className="bolt">↯</div></article></div></section>
      <section className="audience" id="para-quem"><div className="container audience-grid"><div><p className="eyebrow">ONDE A RECARGA FAZ A DIFERENÇA</p><h2>Transforme uma vaga em uma experiência melhor.</h2></div><div className="audience-list"><span>Residências e condomínios</span><span>Hotéis e restaurantes</span><span>Padarias e comércios</span><span>Shoppings e estacionamentos</span><span>Empresas e frotas</span></div></div></section>
      <section className="catalog section" id="catalogo"><div className="container catalog-panel"><div><p className="eyebrow">CATÁLOGO BMAX 2026</p><h2>Encontre o carregador ideal.</h2><p>Conheça as opções residenciais, comerciais e para operações de alta demanda em nosso catálogo inicial.</p></div><a className="button light" href="/catalogo-bmax.pdf" download>Baixar catálogo gratuito <span>↓</span></a></div></section>
      <section className="contact section container" id="contato"><div className="contact-copy"><p className="eyebrow">VAMOS DESENHAR SUA SOLUÇÃO</p><h2>Seu próximo ponto de recarga começa aqui.</h2><p>Conte um pouco sobre o seu projeto. Nossa equipe entrará em contato para orientar a melhor solução.</p></div><form className="lead-form" action="mailto:contato@bmaxtechnology.com.br" method="post" encType="text/plain"><label>Seu nome<input name="nome" placeholder="Como podemos te chamar?" required /></label><label>WhatsApp ou e-mail<input name="contato" placeholder="Seu melhor contato" required /></label><label>Tipo de projeto<select name="projeto" defaultValue=""><option value="" disabled>Selecione uma opção</option><option>Residencial</option><option>Comercial</option><option>Estacionamento / shopping</option><option>Frota / grande operação</option></select></label><button className="button" type="submit">Solicitar orçamento</button><small>Ao enviar, você será direcionado ao seu aplicativo de e-mail.</small></form></section>
      <footer><div className="container footer-inner"><a className="brand" href="#inicio"><span className="brand-mark">B</span><span>Bmax <em>Technology</em></span></a><span>Mobilidade elétrica que faz sentido.</span><span>© 2026 Bmax Technology</span></div></footer>
    </main>
  );
}
